apiVersion: v1
kind: Service
metadata:
  name: gcp-pubsub-adapter
spec:
  selector:
    app: gcp-pubsub-adapter
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
